-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.acclerometer (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  archetype text,
  age integer,
  sex text,
  session_id text,
  activity_label text,
  sample_index integer,
  timestamp_ms double precision,
  ax_g double precision,
  ay_g double precision,
  az_g double precision,
  svm_g double precision,
  dynamic_acc_g double precision,
  dominant_freq_hz double precision,
  step_detected boolean,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT acclerometer_pkey PRIMARY KEY (id),
  CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.gsr_eda (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  archetype text,
  age integer,
  sex text,
  skin_type text,
  stress_condition text,
  sample_index integer,
  timestamp_s double precision,
  eda_raw_voltage_mv double precision,
  eda_microsiemens double precision,
  scl_microsiemens double precision,
  scr_amplitude_microsiemens double precision,
  scr_detected boolean,
  scr_latency_s double precision,
  skin_conductance_category text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gsr_eda_pkey PRIMARY KEY (id),
  CONSTRAINT fk_eda_user FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.gyroscope (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  archetype text,
  age integer,
  sex text,
  session_id text,
  activity_label text,
  sample_index integer,
  timestamp_ms double precision,
  gx_dps double precision,
  gy_dps double precision,
  gz_dps double precision,
  rotation_magnitude_dps double precision,
  motion_intensity text,
  yaw_deg double precision,
  pitch_deg double precision,
  roll_deg double precision,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gyroscope_pkey PRIMARY KEY (id),
  CONSTRAINT fk_motion_user FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.heart_rate_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  archetype text,
  age integer,
  sex text,
  rhr_base_bpm numeric,
  timestamp timestamp without time zone NOT NULL,
  date date,
  hour_of_day integer,
  day_of_week text,
  activity_state text,
  hr_bpm numeric,
  hr_smoothed_bpm numeric,
  signal_quality numeric,
  artifact_flag boolean,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT heart_rate_logs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.ibi (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  archetype text,
  age integer,
  sex text,
  base_ibi_ms double precision,
  activity_state text,
  beat_index integer,
  timestamp_ms double precision,
  ibi_ms double precision,
  successive_diff_ms double precision,
  rmssd_local_ms double precision,
  running_hr_bpm double precision,
  beat_quality_score double precision,
  artifact_flag boolean,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ibi_pkey PRIMARY KEY (id),
  CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  username text UNIQUE,
  created_at timestamp without time zone DEFAULT now(),
  email text,
  user_id text UNIQUE,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.skin_contact (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  archetype text,
  age integer,
  sex text,
  compliance numeric,
  timestamp timestamp without time zone NOT NULL,
  date date,
  hour_of_day integer,
  day_of_week text,
  activity_state text,
  wearing_status text,
  ppg_dc_level double precision,
  ppg_ac_amplitude double precision,
  perfusion_index double precision,
  skin_conductance_proxy_us double precision,
  motion_artifact boolean,
  contact_confidence integer,
  contact_detected boolean,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT skin_contact_pkey PRIMARY KEY (id),
  CONSTRAINT fk_user_wearable FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.skin_temperature (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  archetype text,
  age integer,
  sex text,
  timestamp timestamp without time zone NOT NULL,
  date date,
  hour_of_day integer,
  day_of_week text,
  activity_state text,
  circadian_phase text,
  skin_temp_c numeric,
  ambient_temp_c numeric,
  temp_delta_c numeric,
  menstrual_phase text,
  fever_flag boolean,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT skin_temperature_pkey PRIMARY KEY (id),
  CONSTRAINT fk_user_temperature FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.spo2 (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  archetype text,
  age integer,
  sex text,
  altitude_m numeric,
  timestamp timestamp without time zone NOT NULL,
  date date,
  hour_of_day integer,
  day_of_week text,
  activity_state text,
  ac_red_au numeric,
  dc_red_au numeric,
  ac_ir_au numeric,
  dc_ir_au numeric,
  r_ratio numeric,
  spo2_percent numeric,
  perfusion_index numeric,
  signal_quality numeric,
  motion_artifact boolean,
  respiratory_event text,
  artifact_flag boolean,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT spo2_pkey PRIMARY KEY (id),
  CONSTRAINT fk_spo2_user FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.test (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT test_pkey PRIMARY KEY (id)
);